server:
  port: 8080
  servlet:
    context-path: /api/v1
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mentorflow
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "5549a87579325eddd565206e60790231367c90da4002b14239aa656e2f197c20"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

#cloud
cloudinary:
  cloud-name: dcpj8cfng
  api-key:  918924966822386
  api-secret: AgeAnoSbgJibSGcPeAhUl_-CPEI

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: FNGBVV5L
    secretKey: 7Z1SMW7LFOMEZFH49JQBC46H0Y54I83I
    returnUrl: http://localhost:8080/api/v1/payment/vnpay-return
    version: 2.1.0
    command: pay
    orderType: other
